# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
    ]
