# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_auto_20180326_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'managed': True},
        ),
    ]
